### ISSUE TITLE
clock == 0.5.* fixed?

### ISSUE THREAD

**Issue by luke-clifton** [jystic/hadoop-tools#27]
I vaguely recall there having been some issue with CentOS 6 that was causing us to rely on an old version of clock. But I don't remember exactly what it was.

Does this fix it? https://github.com/corsis/clock/pull/38

**Comment by jystic** [comment]
It may well do, the easy thing to do would be try it out, the circle-ci build will fail if it's broken

**Comment by luke-clifton** [comment]
All seems good.
